[package]
name = "jack_pan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.9.0"
ringbuf = "0.2.7"
itertools = "0.10.3"